-- MySQL Script generated by MySQL Workbench
-- Tue Jul  7 12:37:58 2020
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diariodb` ;
USE `diariodb` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `ContraUsuario` VARCHAR(45) NULL,
  `direcUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

INSERT INTO `usuario` (`idUsuario`, `nombre`, `apellido`, `ContraUsuario`, `direcUsuario`) VALUES ('1010', 'Thor', 'Quispe Quispe', '123456', 'alumno');


-- -----------------------------------------------------
-- Table `new_schema1`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodb`.`Notas` (
  `idNotas` INT NOT NULL,
  `fecha` DATE NULL,
  `nombreNotas` VARCHAR(45) NULL,
  `AggNotas` VARCHAR(1000) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_Notas_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Notas_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `diariodb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- llenado de las tablas usuario
-- -----------------------------------------------------
INSERT INTO `notas` (`idNotas`, `fecha`, `nombreNotas`, `AggNotas`, `Usuario_idUsuario`) VALUES ('01', '2020-07-01', 'HISTORIA DE YOUTUBE', 'YouTube fue fundada por Chad Hurley, Steve Chen y Jawed Karim en febrero de 2005 ', '1010');
INSERT INTO `notas` (`idNotas`, `fecha`, `nombreNotas`, `AggNotas`, `Usuario_idUsuario`) VALUES ('02', '2020-07-02', 'Activación del dominio', 'Llevaron a cabo su idea y el dominio fue activado el 15 de febrero de 2005', '1010');
INSERT INTO `notas` (`idNotas`, `fecha`, `nombreNotas`, `AggNotas`, `Usuario_idUsuario`) VALUES ('03', '2020-07-03', 'Historia de YouTube.', 'YouTube, es un sitio web que permite a los usuarios subir, bajar, ver y compartir vídeos.', '1010');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
